name: 'Continuous integration'

on:
  workflow_dispatch:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2.3.4
        with: 
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.x'

      - name: Run release build (no tests)
        run: dotnet run -- --release --xml-documentation --targets unitTest samples
        working-directory: './Build'
  
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2.3.4
        with: 
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.x'

      - name: Run release build
        run: dotnet run -- --release --xml-documentation --targets unitTest integrationTest samples
        working-directory: './Build'
